# PULL THE BASE IMAGE
FROM python:3.12.4-slim

## SET ENVIRONMENT VARIABLES
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app
COPY requirements.txt /app

# INSTALL DEPENDENCIES
RUN pip install -r requirements.txt

# COPY PROJECT
COPY . ./app
