
services:
  api:
    container_name: mosaic-api
    build: 
      context: .
    ports:
      - 8006:8000
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    volumes:
      - .:/app
    env_file: .env
